name: employee_mobile_app
description: "Employee Mobile App"
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html:
  hive: ^2.2.3
  http: ^1.2.0
  intl:
  html: ^0.15.4
  shimmer: ^3.0.0
  timezone: ^0.9.2
  surf_lint_rules:
  share_plus: ^7.2.2
  flutter_svg: ^2.0.9
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.5.0
  connectivity_plus: ^5.0.2
  very_good_analysis: ^5.1.0
  flutter_local_notifications: ^16.3.2
  shrink_sidemenu: ^2.0.0+2-null-safety
  ecommerce_mobile_login:
    path: ecommerce_mobile_login
  mobile_app_platform_widgets:
    path: mobile_app_platform_widgets
  tyrios_mobile_app_flutter_extensions:
    path: mobile_app_extentions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_intl:
  enabled: true

