name: tyrios_mobile_app_flutter_extensions
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  mobile_app_platform_widgets:
    path: ../mobile_app_platform_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf